#ifndef IO_DEFINITIONS_H_
#define IO_DEFINITIONS_H_

//motors
#define MOTOR_L_M 1
#define MOTOR_L_2 2
#define MOTOR_R_M 10
#define MOTOR_R_2 9
#define MOTOR_SHOOT 3
#define MOTOR_BALL_COLLECTOR 4
#define MOTOR_LIFT_LEFT 5
#define MOTOR_LIFT_RIGHT 6

//encoders
#define ENCODER_LEFT_TOP 1
#define ENCODER_LEFT_BOTTOM 2
#define ENCODER_RIGHT_TOP 3
#define ENCODER_RIGHT_BOTTOM 4

//joystick
#define MASTER_JOYSTICK 1

#define JOYSTICK_ANGULAR_CH 1
#define JOYSTICK_VERTICAL_CH 3
#define JOYSTICK_THROT_START 10

#endif
